//! Static MCP `tools/list` inputSchema JSON for the desktop server.
//! Split out of `mcp_serve.rs` to keep that file under the 800-line cap.

pub const TOOL_SCHEMAS: &[&str] = &[
    // --- read tools ---
    r#"{"name":"open_document","description":"Open the current Rust MCP document, or the TS-compatible filePath target for this call, and return metadata, context summary, and design prompt.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"}}}}"#,
    r#"{"name":"save_document","description":"Save the current Rust MCP document snapshot to a .op file. Used by the Rust HTTP CLI to match TS `op save`; pass sourceFilePath to copy a specific source .op file to the target filePath.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Target .op file path"},"sourceFilePath":{"type":"string","description":"Optional source .op file path for TS-compatible `op save <target> --file <source>`"}},"required":["filePath"]}}"#,
    r#"{"name":"get_document_info","description":"Summarize the open document (page count, active page, etc).","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"get_selection","description":"Return the current selection state (ids, count).","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"readDepth":{"type":"number","description":"How deep to include children in selected nodes; default 2"}}}}"#,
    r#"{"name":"get_node","description":"Read a node by id with depth-limited descendants.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string","description":"u64 node id"}},"required":["node_id"]}}"#,
    r#"{"name":"list_pages","description":"List page ids + names. Result includes page_count, active_page_index, ids, and names as comma-separated strings.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"}}}}"#,
    r#"{"name":"list_variables","description":"List design variables with kinds.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"get_variables","description":"Return all design variables and theme axes as JSON strings. TS-compatible read alias for variables/theme metadata.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"}}}}"#,
    r#"{"name":"upsert_variables","description":"Idempotently merge a converted token source into document variables and record it in the code-to-design conversion ledger.","inputSchema":{"type":"object","properties":{"key":{"type":"string","description":"Stable token source key, e.g. tokens:theme.css"},"variables":{"oneOf":[{"type":"object"},{"type":"string"}],"description":"Variable definitions object, or a JSON string containing that object"},"sourcePath":{"type":"string"},"sourceHash":{"type":"string"}},"required":["key","variables"]}}"#,
    r#"{"name":"upsert_component","description":"Idempotently upsert a converted component master and record it in the code-to-design conversion ledger.","inputSchema":{"type":"object","properties":{"key":{"type":"string","description":"Stable component key, e.g. src/Button.tsx#Button"},"name":{"type":"string"},"node_json":{"oneOf":[{"type":"object"},{"type":"string"}],"description":"Single PenNode component root object, or a JSON string containing it"},"sourcePath":{"type":"string"},"sourceHash":{"type":"string"}},"required":["key","name","node_json"]}}"#,
    r#"{"name":"upsert_screen","description":"Idempotently upsert a converted screen root and record it in the code-to-design conversion ledger.","inputSchema":{"type":"object","properties":{"key":{"type":"string","description":"Stable route key, e.g. route:/settings"},"node_json":{"oneOf":[{"type":"object"},{"type":"string"}],"description":"Single Frame PenNode screen root object, or a JSON string containing it"},"sourcePath":{"type":"string"},"sourceHash":{"type":"string"}},"required":["key","node_json"]}}"#,
    r#"{"name":"conversion_status","description":"Report code-to-design conversion ledger entries and whether component/screen node targets still exist.","inputSchema":{"type":"object","properties":{"kind":{"type":"string","enum":["token","component","screen"],"description":"Optional ledger kind filter"}}}}"#,
    r#"{"name":"lint_document","description":"Run first-class OpenPencil design lint over the active document. Optionally filter to a node subtree.","inputSchema":{"type":"object","properties":{"nodeId":{"type":"string","description":"Optional node id to filter issues to that node and descendants"}}}}"#,
    r#"{"name":"save_theme_preset","description":"Save the current document themes and variables as a reusable .optheme preset file.","inputSchema":{"type":"object","properties":{"presetPath":{"type":"string","description":"Path for the output .optheme file"},"name":{"type":"string","description":"Display name for the preset; defaults to file name"},"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"}},"required":["presetPath"]}}"#,
    r#"{"name":"load_theme_preset","description":"Load a .optheme preset file and merge its themes and variables into the live document.","inputSchema":{"type":"object","properties":{"presetPath":{"type":"string","description":"Path to the .optheme file to load"},"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"}},"required":["presetPath"]}}"#,
    r#"{"name":"list_theme_presets","description":"List valid .optheme preset files in a directory.","inputSchema":{"type":"object","properties":{"directory":{"type":"string","description":"Directory to scan for .optheme files"}},"required":["directory"]}}"#,
    r#"{"name":"get_design_md","description":"Get the document design.md spec and markdown, falling back to best-effort extraction from variables and typography.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"}}}}"#,
    r#"{"name":"set_design_md","description":"Import design.md markdown into the live document, or pass autoExtract=true to derive it from current variables and typography.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"markdown":{"type":"string","description":"Raw design.md markdown"},"autoExtract":{"type":"boolean","description":"Derive design.md from the current document"}}}}"#,
    r#"{"name":"export_design_md","description":"Export design.md markdown, falling back to best-effort extraction when none is persisted.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"}}}}"#,
    r#"{"name":"get_style_guide_tags","description":"Return all available style guide tags for filtering light/dark visual styles.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"get_style_guide","description":"Return a style guide by name or best tag match. Provide tags array/string, name, and optional platform.","inputSchema":{"type":"object","properties":{"tags":{"type":"array","items":{"type":"string"}},"name":{"type":"string"},"platform":{"type":"string","enum":["webapp","mobile","landing-page","slides"]}}}}"#,
    r#"{"name":"list_style_guides","description":"List every style guide the editor can offer: the shipped corpus plus the DESIGN.md files the user imported (imports first). Pass id to fetch one guide with its markdown — get_style_guide reaches the shipped corpus only.","inputSchema":{"type":"object","properties":{"id":{"type":"string","description":"Guide id: a corpus guide's name, or user:<slug> for an import"},"tag":{"type":"string"},"platform":{"type":"string","enum":["webapp","mobile","landing-page","slides"]}}}}"#,
    r#"{"name":"get_guidelines","description":"Return OpenPencil product-design guidelines. Default category is guide, which reads topic. category=style resolves an OpenPencil style using flat scalar string args.","inputSchema":{"type":"object","properties":{"category":{"type":"string","enum":["guide","style"],"default":"guide","description":"guide returns the existing topic guideline path; style resolves the style catalog"},"topic":{"type":"string","enum":["web-app","mobile","code-to-design","landing-page","dashboard","slides","form","design-system","interactivity","scroll","card","icons"],"description":"Guide topic for category=guide"},"name":{"type":"string","description":"Style catalog name for category=style"},"colorPalette":{"type":"string","description":"Style palette name for category=style"},"roundness":{"type":"string","description":"Roundness profile for category=style"},"elevation":{"type":"string","description":"Elevation profile for category=style"},"headings":{"type":"string","description":"Heading font family for category=style"},"body":{"type":"string","description":"Body font family for category=style"},"captions":{"type":"string","description":"Caption font family for category=style"},"data":{"type":"string","description":"Data font family for category=style"},"decorativeImagery":{"type":"string","description":"Optional decorative imagery guidance for category=style"}}}}"#,
    r#"{"name":"spawn_agents","description":"Split a large design task into parallel subtasks. Each config item gives a prompt, the container node(s) to fill, and the styleguide + guideline NAMES to pass to the subagent (subagents cannot search styleguides). Returns the spawned agent ids. Execution runs the subagents in parallel.","inputSchema":{"type":"object","properties":{"config":{"type":"array","items":{"type":"object","properties":{"prompt":{"type":"string"},"containerNodes":{"type":"array","items":{"type":"string"}},"styleguideName":{"type":"string"},"guidelineNames":{"type":"array","items":{"type":"string"}}},"required":["prompt","styleguideName"]}}},"required":["config"]}}"#,
    r#"{"name":"ToolSearch","description":"Discover tools by keyword or exact selection. Use 'select:Name1,Name2' to load specific tools, or a keyword query to search names+descriptions.","inputSchema":{"type":"object","properties":{"query":{"type":"string"},"max_results":{"type":"integer","minimum":1,"default":5}},"required":["query"]}}"#,
    r#"{"name":"get_screenshot","description":"Render a node to a PNG image for visual verification. nodeId may be \"root\" for the active page's top node.","inputSchema":{"type":"object","properties":{"nodeId":{"type":"string","description":"Node id, or \"root\""}},"required":["nodeId"]}}"#,
    r#"{"name":"export_item","description":"Export a page, arbitrary node, or current selection to base64-encoded image/PDF bytes.","inputSchema":{"type":"object","properties":{"itemId":{"type":"string"},"format":{"type":"string","enum":["png","jpeg","webp","pdf"]},"scale":{"type":"number"}},"required":["format"]}}"#,
    r#"{"name":"export_nodes","description":"Export one or more nodes to base64-encoded image/PDF bytes. format is one of png|jpeg|webp|pdf.","inputSchema":{"type":"object","properties":{"nodeIds":{"type":"array","items":{"type":"string"}},"format":{"type":"string","enum":["png","jpeg","webp","pdf"]},"scale":{"type":"number"}},"required":["nodeIds","format"]}}"#,
    r#"{"name":"export_deck","description":"Export the active page's boards as a presentation deck in PowerPoint, self-contained HTML, or PDF. Writes a file at outputPath; use export_item/export_nodes for base64 node-level exports.","inputSchema":{"type":"object","properties":{"format":{"type":"string","enum":["pptx","html","pdf"]},"outputPath":{"type":"string","description":"Destination file path for the deck"}},"required":["format","outputPath"]}}"#,
    r#"{"name":"export_frames","description":"Export every top-level frame on the active page into a directory, one image per frame, using the editor's own file naming.","inputSchema":{"type":"object","properties":{"outputDir":{"type":"string","description":"Destination directory; created if absent"},"format":{"type":"string","enum":["png","jpeg","webp"],"default":"png"}},"required":["outputDir"]}}"#,
    r#"{"name":"get_deck_boards","description":"List the boards on the active page in slide order — what a deck export will walk. Hidden boards are omitted.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"list_scene_templates","description":"List the scene templates available on this deployment. The shipped catalogue is always included; local editors also include templates you saved (saved first, ids prefixed user:). Optionally filter by scene or tag (shipped templates only).","inputSchema":{"type":"object","properties":{"scene":{"type":"string","description":"Scene filter, e.g. slides, tutorial, comparison, carousel"},"tag":{"type":"string","description":"Tag filter"}}}}"#,
    r#"{"name":"use_scene_template","description":"Start from a scene template returned by list_scene_templates. Local editors can also use saved templates whose ids are prefixed user:. On an untouched starter page the template takes the page over; otherwise its boards are appended to the right.","inputSchema":{"type":"object","properties":{"templateId":{"type":"string"}},"required":["templateId"]}}"#,
    r#"{"name":"get_active_theme","description":"Return the active theme axis pinning per axis.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"list_components","description":"List registered components (saved Frames / Groups promoted via Save as Component). Returns count + a `;`-separated record of `name|id` pairs.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"list_ui_kits","description":"List the live editor's UIKit components for script-first K() insertion. Returns kit/component metadata plus each component's canonical scriptRef. Results are globally bounded by limit.","inputSchema":{"type":"object","properties":{"kitId":{"type":"string","description":"Optional exact kit id"},"query":{"type":"string","description":"Optional case-insensitive search across kit/component ids, names, categories, and tags"},"category":{"type":"string","enum":["buttons","inputs","cards","navigation","layout","feedback","data-display","other"]},"limit":{"type":"integer","minimum":1,"maximum":100,"default":50,"description":"Maximum components returned across all kits"}}}}"#,
    r#"{"name":"get_component","description":"Fetch one component by id with detail: name, root node kind, and the subtree's leaf count.","inputSchema":{"type":"object","properties":{"component_id":{"type":"string","description":"positive u64 component id"}},"required":["component_id"]}}"#,
    r#"{"name":"batch_get","description":"Search and read nodes from the document. With no patterns/nodeIds, returns top-level children. Supports type/name regex patterns, nodeIds, parentId, readDepth, searchDepth, and pageId.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"patterns":{"type":"array","items":{"type":"object","properties":{"type":{"type":"string"},"name":{"type":"string"},"reusable":{"type":"boolean"}}}},"nodeIds":{"type":"array","items":{"type":"string"}},"parentId":{"type":"string"},"readDepth":{"type":"number"},"searchDepth":{"type":"number"},"pageId":{"type":"string"},"resolveRefs":{"type":"boolean"},"resolve_refs":{"type":"boolean"}}}}"#,
    r#"{"name":"read_nodes","description":"Read nodes with depth control. Omit nodeIds to return top-level page children; depth=0 truncates children to \"...\", depth=-1 returns full subtrees. includeVariables=true attaches variables/themes JSON strings.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"nodeIds":{"type":"array","items":{"type":"string"},"description":"Node ids to read; omit for top-level children"},"depth":{"type":"number","description":"0=node only, 1=direct children, -1=full subtree"},"pageId":{"type":"string"},"includeVariables":{"type":"boolean"}}}}"#,
    r#"{"name":"codegen_plan","description":"Submit a code generation plan (CodePlanFromAI). The server validates the plan (rejects on duplicate chunkIds, empty nodeIds, unknown dependencies, circular deps, missing nodeIds) and returns a topologically sorted executionPlan with warnings for shared nodeIds. The planId returned is used by codegen_submit_chunk and codegen_assemble.","inputSchema":{"type":"object","properties":{"plan":{"type":"object","description":"CodePlanFromAI: { chunks, sharedStyles, rootLayout }"},"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"pageId":{"type":"string","description":"Target page ID. Default: active page."}},"required":["plan"]}}"#,
    r#"{"name":"codegen_submit_chunk","description":"Submit generated code for one chunk. Returns validation result, progress of all chunks, and the next chunk ready for generation (if any). Resubmitting the same chunkId overrides the previous result.","inputSchema":{"type":"object","properties":{"planId":{"type":"string","description":"Plan ID from codegen_plan."},"result":{"type":"object","description":"ChunkResult: { chunkId, code, contract }"},"status":{"type":"string","enum":["failed","skipped"],"description":"Optional override to mark a chunk failed or skipped. Dependent chunks remain blocked until the dependency is successfully resubmitted."}},"required":["planId","result"]}}"#,
    r#"{"name":"codegen_assemble","description":"Retrieve usable chunk results in topological order for final assembly. Rejects plans with pending chunks and leaves them available. A fully successful result consumes the plan; retryable partial or degraded results retain it for repair and resubmission. Explicit skipped-only partials may be terminal. The result reports degraded, partial, retryable, planRetained, and omittedChunks.","inputSchema":{"type":"object","properties":{"planId":{"type":"string","description":"Plan ID from codegen_plan."},"framework":{"type":"string","enum":["react","vue","svelte","html","flutter","swiftui","compose","react-native"],"description":"Target framework."}},"required":["planId","framework"]}}"#,
    r#"{"name":"codegen_clean","description":"Manually clean up an abandoned codegen plan. Idempotent.","inputSchema":{"type":"object","properties":{"planId":{"type":"string","description":"Plan ID to clean up."}},"required":["planId"]}}"#,
    r#"{"name":"search_all_unique_properties","description":"Recursively search unique style property values under the provided parent node ids. Result `properties` is a JSON object keyed by requested property names.","inputSchema":{"type":"object","properties":{"parents":{"type":"array","items":{"type":"string"},"description":"Parent node ids to search; descendants and the parent itself are included"},"properties":{"type":"array","items":{"type":"string","enum":["fillColor","textColor","strokeColor","strokeThickness","cornerRadius","padding","gap","fontSize","fontFamily","fontWeight"]}},"pageId":{"type":"string"},"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"}},"required":["parents","properties"]}}"#,
    r#"{"name":"replace_all_matching_properties","description":"Recursively replace matching style property values under parent node ids. Returns replacedCount and applies one bulk edit when matches exist.","inputSchema":{"type":"object","properties":{"parents":{"type":"array","items":{"type":"string"}},"properties":{"type":"object","description":"property -> array of {from,to} replacement rules"},"pageId":{"type":"string"},"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"}},"required":["parents","properties"]}}"#,
    r#"{"name":"snapshot_layout","description":"Get the hierarchical bounding box layout tree of the document. Use this to understand the current page structure, spatial arrangement, and node hierarchy before making changes.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"parentId":{"type":"string","description":"Only return layout under this parent node"},"maxDepth":{"type":"number","description":"Max depth to traverse (default 1)"},"pageId":{"type":"string","description":"Target page ID (defaults to the active page)"}}}}"#,
    r#"{"name":"find_empty_space","description":"Find padded empty canvas space in one direction for placing new content.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"width":{"type":"string","description":"i32 doc-px"},"height":{"type":"string","description":"i32 doc-px"},"padding":{"type":"string","description":"i32 doc-px, default 50"},"direction":{"type":"string","enum":["top","right","bottom","left"]},"nodeId":{"type":"string"},"pageId":{"type":"string"}},"required":["width","height","direction"]}}"#,
    r#"{"name":"get_canvas_bounds","description":"Return the union bounding box of every top-level node on the active page (x/y/w/h ints + has_content true/false).","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"find_node_by_name","description":"Locate the first node whose name matches (case-sensitive, exact) anywhere on the active page. Returns id + kind. ToolFailed when no match.","inputSchema":{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}}"#,
    r#"{"name":"get_node_parent","description":"Return the parent id of node_id on the active page. parent_id=0 means the node is at the page root. depth is distance from root.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string","description":"positive u64 node id"}},"required":["node_id"]}}"#,
    r#"{"name":"get_node_children","description":"List the immediate children of a node. Returns count + comma-separated ids + per-child (child_<i>_id/kind/name/x/y/width/height). Known leaves and empty containers return count=0 (NOT an error). Only an unknown node_id returns ToolFailed.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string","description":"positive u64 node id"}},"required":["node_id"]}}"#,
    r#"{"name":"count_nodes","description":"Return total node count across all pages + a per-page breakdown. Result `per_page` is `;`-separated `index|count` records.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"list_node_kinds","description":"Return a per-kind histogram of nodes on the active page (frame/group/rect/ellipse/polygon/line/text/path/other). Result `kinds` is `;`-separated `kind|count` records.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"get_history_depth","description":"Return undo + redo stack sizes. Useful before bulk rollback to know how many steps are available.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"get_viewport","description":"Return current canvas pan + zoom. pan_x/pan_y are i32 doc-px; zoom_percent is the zoom * 100 as int.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"get_selection_set","description":"Return every id in the multi-select set (vs get_selection which returns only the anchor). Result: count + comma-separated ids + anchor.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"get_editor_state","description":"Consolidated editor snapshot: active page, selection, top-level nodes, and components. The recommended FIRST call when starting a design task.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"get_design_quality","description":"Run the design agent's non-destructive quality diagnostics over the current document. Returns separate geometry, layout, contrast, icon, structure, empty-shell, intent, variable, image-slot, and navigation issue arrays. Never repairs or changes editor state.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"clear_selection","description":"Drop the current multi-select. No args.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"set_selection","description":"Set selection to a single node by id (scoped to the ACTIVE page only). Rejects unknown ids and ids that live on a non-active page — switch the active page first with set_active_page.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string","description":"positive u64 node id on the active page"}},"required":["node_id"]}}"#,
    r#"{"name":"set_viewport","description":"Set canvas pan + zoom. Pass any subset of pan_x / pan_y / zoom_percent — omitted axes are left unchanged. zoom_percent clamps to [10, 2000].","inputSchema":{"type":"object","properties":{"pan_x":{"type":"string","description":"i32 doc-px"},"pan_y":{"type":"string","description":"i32 doc-px"},"zoom_percent":{"type":"string","description":"int * 100 (100 == 1.0×)"}}}}"#,
    r#"{"name":"set_node_hidden","description":"Toggle a node's visibility (layer-panel eye icon). value is \"true\" to hide.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"value":{"type":"string","enum":["true","false"]}},"required":["node_id","value"]}}"#,
    r#"{"name":"set_node_locked","description":"Toggle a node's lock (layer-panel padlock icon). value is \"true\" to lock.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"value":{"type":"string","enum":["true","false"]}},"required":["node_id","value"]}}"#,
    r#"{"name":"set_node_collapsed","description":"Toggle a node's layer-panel disclosure state. value is \"true\" to collapse.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"value":{"type":"string","enum":["true","false"]}},"required":["node_id","value"]}}"#,
    r#"{"name":"set_active_tool","description":"Change the active canvas tool (left toolbar). Accepts select / rect / ellipse / polygon / line / pen / text / frame / hand.","inputSchema":{"type":"object","properties":{"tool":{"type":"string","enum":["select","rect","ellipse","polygon","line","pen","text","frame","hand"]}},"required":["tool"]}}"#,
    r#"{"name":"undo","description":"Pop the last history snapshot. Returns false when the past stack is empty.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"redo","description":"Push the last undone snapshot back. Returns false when the redo stack is empty.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"duplicate_selected","description":"Duplicate the currently-selected node and select the clone. Optional offset_px shifts the clone (default 10).","inputSchema":{"type":"object","properties":{"offset_px":{"type":"string","description":"i32 doc-px shift (default 10)"}}}}"#,
    r#"{"name":"delete_selected","description":"Delete the currently-selected node. Returns false when nothing is selected. Undoable.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"nudge_selected","description":"Translate the currently-selected node by (dx, dy) doc-px. Both 0 rejects.","inputSchema":{"type":"object","properties":{"dx":{"type":"string","description":"i32 doc-px"},"dy":{"type":"string","description":"i32 doc-px"}},"required":["dx","dy"]}}"#,
    r#"{"name":"group_selected","description":"Wrap the multi-selected siblings in a new Group. Cmd+G equivalent. Rejects when selection is empty / single / spans parents.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"ungroup_selected","description":"Replace the selected Group with its children. Cmd+Shift+G equivalent. Rejects when anchor is not a Group.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"reorder_selected","description":"Move the currently-selected node forward (\"up\") or back (\"down\") in z-order. Mirrors layer-panel [ / ].","inputSchema":{"type":"object","properties":{"direction":{"type":"string","enum":["up","down"]}},"required":["direction"]}}"#,
    r#"{"name":"set_node_rotation","description":"Set node rotation in degrees on a node by id.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"degrees":{"type":"string","description":"finite f32 rotation in degrees"}},"required":["node_id","degrees"]}}"#,
    r#"{"name":"set_node_text","description":"Set text content on a Text-kind node by id. Rejects non-Text kinds.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"text":{"type":"string"}},"required":["node_id","text"]}}"#,
    r#"{"name":"set_node_corner_radius","description":"Set corner-radius (non-negative doc-px) on a node by id. Honored at paint time for Rect / Frame; other kinds accept the write but the radius is invisible.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"radius":{"type":"string","description":"non-negative finite f32"}},"required":["node_id","radius"]}}"#,
    r#"{"name":"set_node_font_size","description":"Set font size (positive finite doc-px) on a Text-kind node by id. Rejects non-Text kinds.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"font_size":{"type":"string","description":"positive finite f32 doc-px"}},"required":["node_id","font_size"]}}"#,
    r#"{"name":"set_node_font_weight","description":"Set OpenType font weight (1..=1000) on a Text-kind node by id. Rejects non-Text kinds and out-of-range weights.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"font_weight":{"type":"string","description":"u16 in 1..=1000 (e.g. 400=Regular, 700=Bold)"}},"required":["node_id","font_weight"]}}"#,
    r##"{"name":"set_node_stroke_hex","description":"Set the stroke color on a node. Existing stroke gets its color overwritten; missing stroke gets a fresh 1 doc-px stroke attached at the parsed color so the change is visible immediately.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"hex":{"type":"string","description":"#rgb / #rrggbb / #rrggbbaa"}},"required":["node_id","hex"]}}"##,
    r#"{"name":"set_node_stroke_width","description":"Set the stroke width (doc-px) on a node. width=0 clears the stroke; width>0 on a node without an existing stroke attaches a fresh black-default stroke at that width.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"width":{"type":"string","description":"non-negative finite f32 doc-px"}},"required":["node_id","width"]}}"#,
    r#"{"name":"set_node_stroke_side_width","description":"Set ONE side's stroke width (doc-px) on a node, leaving the other sides intact. Use for one-sided borders / underlines (e.g. side=bottom for an underline). Promotes a uniform stroke to its per-side form at apply time.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"side":{"type":"string","enum":["top","right","bottom","left"]},"width":{"type":"string","description":"non-negative finite f32 doc-px"}},"required":["node_id","side","width"]}}"#,
    r#"{"name":"align_selected","description":"Align or distribute the current multi-selection. Mirrors the PropertyPanel Align section. Distribute variants silently no-op for fewer than 3 selected nodes.","inputSchema":{"type":"object","properties":{"action":{"type":"string","description":"one of left, center_h, right, top, center_v, bottom, distribute_h, distribute_v"}},"required":["action"]}}"#,
    r##"{"name":"set_node_fill_hex","description":"Set the fill color on a node by id. Sister tool to set_node_stroke_hex; one-call color change without the other update_node fields.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"hex":{"type":"string","description":"#rgb / #rrggbb / #rrggbbaa"}},"required":["node_id","hex"]}}"##,
    r#"{"name":"set_node_flip","description":"Mirror a node horizontally / vertically. Pass any subset of flip_x / flip_y as \"true\"/\"false\"; omitted axes are left unchanged. At least one axis is required.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"flip_x":{"type":"string","enum":["true","false"]},"flip_y":{"type":"string","enum":["true","false"]}},"required":["node_id"]}}"#,
    r#"{"name":"set_ellipse_arc","description":"Set arc geometry on an Ellipse node: start_angle / sweep_angle (degrees) carve a pie/arc, inner_radius (0.0..=1.0 fraction) carves a donut hole. Pass any subset; omitted fields are left unchanged. Rejects non-Ellipse kinds.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"start_angle":{"type":"string","description":"finite degrees"},"sweep_angle":{"type":"string","description":"finite degrees"},"inner_radius":{"type":"string","description":"0.0..=1.0 fraction"}},"required":["node_id"]}}"#,
    r#"{"name":"add_node_effect","description":"Append a visual effect to a node with default parameters. kind is shadow / blur / background_blur. Frame/Group/Rectangle and the leaf shapes accept effects; IconFont/Ref do not.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"kind":{"type":"string","enum":["shadow","blur","background_blur"]}},"required":["node_id","kind"]}}"#,
    r#"{"name":"remove_node_effect","description":"Remove the effect at a 0-based index from a node's effect list. The list is cleared once empty.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"index":{"type":"string","description":"0-based u32 effect index"}},"required":["node_id","index"]}}"#,
    r#"{"name":"set_node_name","description":"Rename a node by id. Empty names (after trim) are rejected so the LayerPanel never shows blank rows.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string"},"name":{"type":"string"}},"required":["node_id","name"]}}"#,
    r#"{"name":"set_selection_set","description":"Replace the multi-selection (active page only) with the supplied comma-separated node_ids. Empty list clears the selection. Unknown ids AND ids that live on a non-active page drop silently.","inputSchema":{"type":"object","properties":{"node_ids":{"type":"string","description":"comma-separated positive u64 active-page node ids; empty string clears"}},"required":["node_ids"]}}"#,
    r#"{"name":"toggle_node_selection","description":"Shift-click parity: toggle node_id in the multi-selection (scoped to the ACTIVE page only). Already-selected ⇒ remove (anchor reassigns to last surviving id); otherwise add as new anchor. Rejects unknown ids and ids that live on a non-active page.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string","description":"positive u64 node id on the active page"}},"required":["node_id"]}}"#,
    r#"{"name":"cycle_active_axis_value","description":"Advance the active value for a theme axis to its next entry (wrapping back to the first). Seeds the axis to its first value when nothing is set. Rejects unknown axes and axes whose values list is empty.","inputSchema":{"type":"object","properties":{"axis":{"type":"string","description":"theme axis name (e.g. \"mode\", \"density\")"}},"required":["axis"]}}"#,
    r#"{"name":"copy_selected","description":"Cmd+C parity. Deep-clones the active-page selection into the document's internal clipboard. Apply-time false when nothing is selected.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"cut_selected","description":"Cmd+X parity. Copies the selection then deletes it. History snapshot pushed so undo restores both clipboard and tree.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"paste_clipboard","description":"Cmd+V parity. Pastes the document clipboard as top-level siblings on the active page, offset by offset_px doc-px (defaults to 10). Mints fresh ids past max_node_id(). Replaces selection with the new ids. Apply-time false when the clipboard is empty or id-space is exhausted.","inputSchema":{"type":"object","properties":{"offset_px":{"type":"string","description":"i32 doc-px offset; defaults to 10 when omitted"}},"required":[]}}"#,
    // --- write tools ---
    r##"{"name":"set_variable_color","description":"Set a Color-kind variable's value.","inputSchema":{"type":"object","properties":{"name":{"type":"string"},"hex":{"type":"string","description":"#rgb / #rrggbb / #rrggbbaa"}},"required":["name","hex"]}}"##,
    r#"{"name":"batch_design","description":"Insert or refine design content. BUILD PROTOCOL: generate every new UI tree with script — a JavaScript program calling I(parent,node) or K(kitRef,parent,overrides), using const/let, helpers, data arrays, and loops. operations is ONLY the edit/refine surface for existing nodes: U/C/R/G/M/D. nodes_json stays accepted for simple leaf compatibility. Transactional: if any operation fails, NONE of the batch is applied (the document is unchanged) and errors[] lists every failing line — fix them and resend the whole batch. Keep each call to <=25 operations; split large screens into logical section batches.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"nodes_json":{"type":"string","description":"JSON array of simple leaf descriptors"},"operations":{"type":"string","description":"Edit/refine existing nodes with U(\"n1\",{\"x\":10}), D(\"n1\"), M(\"n1\",null), copy=C(\"n1\",null,{...}), replacement=R(\"n1\",{...}), or G(...) image fills. The default G target must be an existing EMPTY slot; append is accepted only on a horizontal/vertical layout parent. Do not use I() here; create fresh UI trees with script."},"script":{"type":"string","description":"JavaScript program run in a sandboxed QuickJS: build nodes by calling I(parent,obj) or K(kitRef,parent,overrides), with loops and data arrays allowed. C/U/D/M/R/G are rejected here with an instruction to use operations; console is a no-op. Expands to the operations DSL. Mutually exclusive with nodes_json/operations. Limits: 256 KiB source, 4096 inserts, 2s, 64 MiB, 8 MiB recorded output."},"postProcess":{"type":"boolean"},"canvasWidth":{"type":"number"},"pageId":{"type":"string"}}}}"#,
    r#"{"name":"get_design_prompt","description":"Get OpenPencil design-generation prompt knowledge. Pass section for a focused subset; omit it for all sections. style and design-md are derived from the live document's design.md when present.","inputSchema":{"type":"object","properties":{"section":{"type":"string","description":"Prompt section name, e.g. all, layout, style, design-md, elements, codegen-react"},"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"}},"required":[]}}"#,
    r#"{"name":"get_design_agent_prompt","description":"Return OpenPencil's complete task-matched design-agent system prompt, including resolved product-design depth and a host-aware verification protocol.","inputSchema":{"type":"object","properties":{"userMessage":{"type":"string","description":"The user's design request used to resolve domain and product-depth skills"},"verifyProtocol":{"type":"string","enum":["screenshot","layout"],"default":"screenshot","description":"screenshot requires visual verification; layout uses snapshot_layout for hosts without rendering"}},"required":["userMessage"]}}"#,
    r#"{"name":"design_skeleton","description":"Layered design workflow phase 1: create a root frame plus section frames. Accepts TS-style rootFrame/sections plus optional canvasWidth/pageId; legacy nodes_json/operations payloads remain accepted for compatibility.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"rootFrame":{"type":"object","description":"Root frame definition: name, width, height, layout, gap, fill, padding"},"sections":{"type":"array","items":{"type":"object"},"description":"Section frame definitions; each item needs name and may include height, layout, padding, gap, fill, role, justifyContent, alignItems"},"styleGuide":{"type":"object","description":"Optional style guide metadata"},"canvasWidth":{"type":"number","description":"Canvas width for section contentWidth estimates"},"pageId":{"type":"string","description":"Target page ID or index"},"nodes_json":{"type":"string","description":"Legacy JSON array of simple leaf descriptors"},"operations":{"type":"string","description":"Legacy TS batch_design DSL"}},"required":["rootFrame","sections"]}}"#,
    r#"{"name":"design_content","description":"Layered design workflow phase 2: fill child nodes into a section frame created by design_skeleton. Accepts TS-style sectionId/children plus optional postProcess/canvasWidth/pageId; legacy nodes_json/operations payloads remain accepted for compatibility.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"sectionId":{"type":"string","description":"ID of the section frame from design_skeleton"},"children":{"type":"array","items":{"type":"object"},"description":"Child node definitions to insert under the section"},"postProcess":{"type":"boolean","description":"Apply post-processing after insertion; default true in the TS MCP"},"canvasWidth":{"type":"number","description":"Canvas width for post-processing; default 1200"},"pageId":{"type":"string","description":"Target page ID or index"},"nodes_json":{"type":"string","description":"Legacy JSON array of simple leaf descriptors"},"operations":{"type":"string","description":"Legacy TS batch_design DSL with I(parent,nodeJson) inserts or single U/D/M refine op"}},"required":["sectionId","children"]}}"#,
    r#"{"name":"design_refine","description":"Layered design workflow phase 3: polish an existing design root. Accepts rootId plus optional canvasWidth/pageId and runs deterministic cleanup; legacy nodes_json/operations payloads remain accepted for compatibility.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"rootId":{"type":"string","description":"ID of the root frame to refine"},"canvasWidth":{"type":"number","description":"Canvas width for cleanup heuristics"},"pageId":{"type":"string","description":"Target page ID or index"},"nodes_json":{"type":"string","description":"Legacy JSON array of simple leaf descriptors"},"operations":{"type":"string","description":"Legacy TS batch_design DSL"}}}}"#,
    r#"{"name":"finalize_design","description":"Run OpenPencil's post-generation repair passes over the document — the same deterministic cleanup the built-in design agent applies after a generation (app-shell reshaping, flat table regrouping, duplicate chrome dedupe, text contrast, geometry/overflow, palette polarity, empty image-slot materialization, and more). Call this ONCE after your batch_design / design_skeleton / design_content program(s) succeed and BEFORE presenting the result to the user, then call enrich_images to fill authorized image slots. This tool BLOCKS until the passes finish and saves the repaired document. It is idempotent: calling it twice on an already-finalized document applies (near) zero further repairs. Returns a human-readable repair summary, complete, blockingAdvisoryCount, and advisories. You MUST NOT present the design as finished while complete=false: fix every advisory with batch_design/update_node and call finalize_design again. root_ids optionally scopes the per-root passes; omitted = every top-level frame on the active page.","inputSchema":{"type":"object","properties":{"root_ids":{"type":"array","items":{"type":"string"},"description":"Optional node ids to run the per-root passes on (a JSON array; a comma-separated string is also accepted). Omit to finalize every top-level frame on the active page."}},"required":[]}}"#,
    r#"{"name":"enrich_images","description":"Fill every unresolved image slot on the active page with a real stock photo (Openverse, Wikimedia fallback) — the in-process version of the openpencil-desktop --enrich-images pass. Call after finalize_design and before presenting the result. Search-only: slots bound with an explicit Generate prompt are counted as failed and are NEVER silently converted to a stock search; Auto and Search slots resolve through stock search, one search + one write-back per slot. This tool BLOCKS synchronously until every slot is resolved, the timeout_seconds budget is spent, or no targets remain; slots not started before the budget ran out are reported as unresolved. Returns {\"targets\", \"resolved\", \"failed\", \"unresolved\"}.","inputSchema":{"type":"object","properties":{"timeout_seconds":{"type":"number","description":"Overall wall-clock budget in seconds; default 120, maximum 600"},"root_ids":{"type":"array","items":{"type":"string"},"description":"Optional node ids to scope the fill to those subtrees (a JSON array; a comma-separated string is also accepted). Omit to fill the whole active page."}},"required":[]}}"#,
    r#"{"name":"run_design_agent","description":"Run OpenPencil's built-in design agent loop headlessly against the active document: the same skills-assembled system prompt, 15-tool loop (batch_design / get_screenshot visual verification / style guides), turn caps, and loop-end finalize backstop the desktop App uses for a new design. The provider and API key come from the daemon's persisted agent settings, never from this request. The finished design replaces the document's top-level frames atomically; a pre-flight error, timeout, or empty result leaves the document unchanged. This tool BLOCKS until the loop finishes or timeout_seconds elapses. Returns {\"toolCalls\", \"stopReason\", \"landedRoots\", \"finalize\"}. Call enrich_images afterwards to fill authorized image slots.","inputSchema":{"type":"object","properties":{"brief":{"type":"string","description":"The design request, verbatim user intent"},"timeout_seconds":{"type":"number","description":"Overall wall-clock budget in seconds; default 600, maximum 1800"},"max_turns":{"type":"number","description":"Optional agent-loop turn cap override; default 28"},"provider_id":{"type":"string","description":"Optional saved builtin provider id; default: first ready provider"},"model":{"type":"string","description":"Optional saved model id on that provider; default: its first model"}},"required":["brief"]}}"#,
    r#"{"name":"set_variable_number","description":"Set a Number-kind variable's value (decimal, may be negative or fractional).","inputSchema":{"type":"object","properties":{"name":{"type":"string"},"value":{"type":"string"}},"required":["name","value"]}}"#,
    r#"{"name":"set_variable_string","description":"Set a String-kind variable's value (free-form text).","inputSchema":{"type":"object","properties":{"name":{"type":"string"},"value":{"type":"string"}},"required":["name","value"]}}"#,
    r#"{"name":"set_variable_boolean","description":"Set a Boolean-kind variable's value (\"true\" or \"false\").","inputSchema":{"type":"object","properties":{"name":{"type":"string"},"value":{"type":"string","enum":["true","false"]}},"required":["name","value"]}}"#,
    r#"{"name":"set_variables","description":"Add/update or replace the document variables map. Accepts TS-style variables object and optional replace boolean.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"variables":{"type":"object","description":"name -> { type, value } variable definitions"},"replace":{"type":"boolean","description":"Replace all variables instead of merging"}},"required":["variables"]}}"#,
    r#"{"name":"apply_design_system","description":"Apply a bundled design-system preset (halo, lunaris, nitro, shadcn): writes its full shadcn-vocabulary variable table (Light+Dark themed) plus the Mode theme axis in one undoable step. Reference tokens afterwards as $--primary / $--card / $--muted-foreground.","inputSchema":{"type":"object","properties":{"name":{"type":"string","enum":["halo","lunaris","nitro","shadcn"],"description":"Preset name"}},"required":["name"]}}"#,
    r#"{"name":"set_themes","description":"Add/update or replace theme axes. Accepts TS-style themes object and optional replace boolean.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"themes":{"type":"object","description":"axis name -> variant names array"},"replace":{"type":"boolean","description":"Replace all theme axes instead of merging"}},"required":["themes"]}}"#,
    r##"{"name":"create_variable","description":"Create a new design-token variable. kind is color/number/boolean/string; default_value is parsed per kind (hex for color, decimal for number, true/false for boolean, free text for string). Rejects empty/duplicate names and bad defaults.","inputSchema":{"type":"object","properties":{"name":{"type":"string"},"kind":{"type":"string","enum":["color","number","boolean","string"]},"default_value":{"type":"string","description":"hex / decimal / true|false / text per kind"}},"required":["name","kind","default_value"]}}"##,
    r#"{"name":"delete_variable","description":"Delete a design-token variable by name. Also drops any node $ref pointing at it. Rejects unknown names.","inputSchema":{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}}"#,
    r#"{"name":"rename_variable","description":"Rename a design-token variable and rewrite every node $ref pointing at it. Rejects unknown old_name, empty new_name, or a new_name colliding with a different variable.","inputSchema":{"type":"object","properties":{"old_name":{"type":"string"},"new_name":{"type":"string"}},"required":["old_name","new_name"]}}"#,
    r#"{"name":"instantiate_component","description":"Drop a clone of a registered component's root subtree onto the active page. component_id is the id returned by list_components.","inputSchema":{"type":"object","properties":{"component_id":{"type":"string","description":"positive u64 component id"}},"required":["component_id"]}}"#,
    r#"{"name":"create_component","description":"Promote an existing Frame or Group on the active page to a registered component. Use list_components afterwards to see it, instantiate_component to drop a clone.","inputSchema":{"type":"object","properties":{"node_id":{"type":"string","description":"positive u64 node id"},"name":{"type":"string"}},"required":["node_id","name"]}}"#,
    r#"{"name":"delete_component","description":"Remove a component from the registry by id. Live instances already on the page are NOT affected — they're independent clones.","inputSchema":{"type":"object","properties":{"component_id":{"type":"string","description":"positive u64 component id"}},"required":["component_id"]}}"#,
    r#"{"name":"rename_component","description":"Rename a registered component. Name must be non-empty / non-whitespace.","inputSchema":{"type":"object","properties":{"component_id":{"type":"string","description":"positive u64 component id"},"name":{"type":"string"}},"required":["component_id","name"]}}"#,
    r#"{"name":"set_active_page","description":"Switch which page is the active target for subsequent inserts / batch_design / design_* commands. index is 0-based.","inputSchema":{"type":"object","properties":{"index":{"type":"string","description":"0-based page index"}},"required":["index"]}}"#,
    r#"{"name":"add_page","description":"Append a fresh page and switch the active page to it. Optional name and children mirror the TS MCP page tool. Returns false on id-space exhaustion or an empty name.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"name":{"type":"string","description":"Page name (default: Page N)"},"children":{"type":"array","items":{"type":"object"},"description":"Initial child nodes for the new page; omitted creates the default blank frame"}}}}"#,
    r#"{"name":"rename_page","description":"Set a page's display name. Accepts TS-style pageId or legacy index. Name must be non-empty / non-whitespace.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"pageId":{"type":"string","description":"Page id returned by list_pages"},"index":{"type":"string","description":"0-based page index (legacy)"},"name":{"type":"string"}},"required":["name"]}}"#,
    r#"{"name":"delete_page","description":"Remove a page by index or pageId. The applier keeps the active page valid (clamps if needed).","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"pageId":{"type":"string","description":"Page id returned by list_pages"},"index":{"type":"string","description":"0-based page index (legacy)"}}}}"#,
    r#"{"name":"remove_page","description":"TS-compatible alias for delete_page. Removes a page by pageId or index.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"pageId":{"type":"string","description":"Page id returned by list_pages"},"index":{"type":"string","description":"0-based page index"}}}}"#,
    r#"{"name":"duplicate_page","description":"Clone a page and switch the active page to the clone. Accepts TS-style pageId or legacy index; optional name overrides the clone name.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"pageId":{"type":"string","description":"Page id returned by list_pages"},"index":{"type":"string","description":"0-based page index (legacy)"},"name":{"type":"string","description":"Optional clone name"}}}}"#,
    r#"{"name":"reorder_page","description":"Move a page. Accepts TS-style pageId + index or legacy from + to. Target is clamped to [0, page_count).","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"pageId":{"type":"string","description":"Page id returned by list_pages"},"index":{"type":"string","description":"0-based target page index"},"from":{"type":"string","description":"0-based source page index (legacy)"},"to":{"type":"string","description":"0-based target page index (legacy)"}}}}"#,
    r#"{"name":"set_active_axis_value","description":"Pin a theme axis to one of its allowed values.","inputSchema":{"type":"object","properties":{"axis":{"type":"string"},"value":{"type":"string"}},"required":["axis","value"]}}"#,
    r#"{"name":"insert_node","description":"Create a new leaf node on the active or requested page. Accepts Rust flat fields or TS-style data object.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"kind":{"type":"string","enum":["frame","group","rect","ellipse","polygon","line","text","path"]},"name":{"type":"string"},"x":{"type":"string"},"y":{"type":"string"},"width":{"type":"string"},"height":{"type":"string"},"fill_hex":{"type":"string"},"parent":{"type":"string","description":"optional parent node id; empty/0/null/root omitted = page root"},"data":{"type":"object","description":"TS-style PenNode data; rich fields are preserved as a subtree"},"postProcess":{"type":"boolean","description":"Accepted for TS compatibility; Rust leaf insert path ignores post-processing"},"canvasWidth":{"type":"number","description":"Accepted for TS compatibility; Rust leaf insert path ignores post-processing width"},"pageId":{"type":"string","description":"optional target page id or legacy page index; omitted = active page"}}}}"#,
    r#"{"name":"update_node","description":"Patch fields on an existing node. Accepts Rust flat fields or TS-style nodeId + data object.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"node_id":{"type":"string"},"nodeId":{"type":"string"},"x":{"type":"string"},"y":{"type":"string"},"width":{"type":"string"},"height":{"type":"string"},"name":{"type":"string"},"fill_hex":{"type":"string"},"data":{"type":"object","description":"TS-style shallow patch data; rich fields such as content/fontSize are preserved"},"postProcess":{"type":"boolean","description":"Accepted for TS compatibility; Rust patch path ignores post-processing"},"canvasWidth":{"type":"number","description":"Accepted for TS compatibility; Rust patch path ignores post-processing width"},"pageId":{"type":"string","description":"optional target page id or legacy page index; omitted = active page"}}}}"#,
    r#"{"name":"import_svg","description":"Parse an SVG document and insert the resulting nodes on the active or requested page. Accepts inline svg or TS-style svgPath. Supports rect/circle/ellipse/line/polyline/polygon and path (M/L/H/V/C/S/Q/T/Z).","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"svg":{"type":"string","description":"SVG document text"},"svgPath":{"type":"string","description":"local SVG file path"},"x":{"type":"string","description":"i32 doc-px x offset (default 0)"},"y":{"type":"string","description":"i32 doc-px y offset (default 0)"},"parent":{"type":"string","description":"optional parent node id; empty/0/root omitted = page root"},"maxDim":{"type":"number","description":"Accepted for TS compatibility; Rust SVG path currently preserves parsed dimensions"},"postProcess":{"type":"boolean","description":"Accepted for TS compatibility; Rust SVG path ignores post-processing"},"canvasWidth":{"type":"number","description":"Accepted for TS compatibility; Rust SVG path ignores post-processing width"},"pageId":{"type":"string","description":"optional target page id or legacy page index; omitted = active page"}}}}"#,
    r#"{"name":"import_html","description":"Parse an HTML document or snippet with author/UA cascade, inline and linked stylesheets, CSS variables, media queries, structural selectors, pseudo-elements, flex and editable grid approximation; then insert editable nodes on the active or requested page. Accepts inline html or htmlPath.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"html":{"type":"string","description":"HTML document or fragment text"},"htmlPath":{"type":"string","description":"local HTML file path"},"x":{"type":"string","description":"i32 doc-px x offset (default 0)"},"y":{"type":"string","description":"i32 doc-px y offset (default 0)"},"parent":{"type":"string","description":"optional parent node id; empty/0/root omitted = page root"},"pageId":{"type":"string","description":"optional target page id or legacy page index; omitted = active page"},"viewportHeight":{"type":"string","description":"optional import viewport height in CSS px (default: viewport width * 0.625); drives vh units and height media queries"}}}}"#,
    r#"{"name":"import_html_url","description":"Fetch a web page server-side (SSRF-guarded, public hosts only unless allowlisted) and insert it as editable auto-layout nodes. Static fetch: no JS execution; SPA pages may import incomplete.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"url":{"type":"string","description":"http(s) page URL"},"x":{"type":"string","description":"i32 doc-px x offset (default 0)"},"y":{"type":"string","description":"i32 doc-px y offset (default 0)"},"parent":{"type":"string","description":"optional parent node id; empty/0/root omitted = page root"},"pageId":{"type":"string","description":"optional target page id or legacy page index; omitted = active page"},"viewportHeight":{"type":"string","description":"optional import viewport height in CSS px (default: viewport width * 0.625); drives vh units and height media queries"}}}}"#,
    r#"{"name":"import_web_snapshot","description":"Import a page snapshot JSON produced by the OpenPencil browser extractor script (getComputedStyle + layout boxes) as pixel-accurate absolutely-positioned nodes. The right path for SPA/complex-CSS pages.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"snapshot":{"type":"string","description":"snapshot JSON text (contract v1)"},"snapshotPath":{"type":"string","description":"local snapshot .json file path"},"x":{"type":"string","description":"i32 doc-px x offset (default 0)"},"y":{"type":"string","description":"i32 doc-px y offset (default 0)"},"parent":{"type":"string","description":"optional parent node id; empty/0/root omitted = page root"},"pageId":{"type":"string","description":"optional target page id or legacy page index; omitted = active page"}}}}"#,
    r#"{"name":"delete_node","description":"Remove a node + descendants from its parent. Accepts Rust node_id or TS nodeId, plus optional pageId.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"node_id":{"type":"string"},"nodeId":{"type":"string"},"pageId":{"type":"string","description":"optional target page id or legacy page index; omitted = active page"}}}}"#,
    r#"{"name":"move_node","description":"Reparent a node. Accepts Rust node_id/target_parent_id or TS nodeId/parent, plus optional index and pageId.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"node_id":{"type":"string"},"nodeId":{"type":"string"},"target_parent_id":{"type":"string"},"parent":{"type":"string","description":"target parent node id; empty/0/null/root omitted = page root"},"index":{"type":"string","description":"optional insertion index within target parent/root"},"pageId":{"type":"string","description":"optional target page id or legacy page index; omitted = active page"}}}}"#,
    r#"{"name":"copy_node","description":"Deep-clone a subtree with fresh ids under a new parent. Accepts Rust node_id or TS sourceId/nodeId, plus optional parent/overrides/pageId.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"node_id":{"type":"string"},"sourceId":{"type":"string"},"nodeId":{"type":"string"},"target_parent_id":{"type":"string"},"parent":{"type":"string","description":"target parent node id; empty/0/null/root omitted = page root"},"overrides":{"type":"object","description":"TS-style shallow properties to apply to the cloned root; id is ignored"},"pageId":{"type":"string","description":"optional target page id or legacy page index; omitted = active page"}}}}"#,
    r#"{"name":"replace_node","description":"Swap an existing node at the same parent slot with a freshly-built leaf. Accepts Rust flat fields or TS-style nodeId + data object. Set drop_children=true to discard a container's subtree.","inputSchema":{"type":"object","properties":{"filePath":{"type":"string","description":"Optional target .op file path; omit to use the server document"},"node_id":{"type":"string"},"nodeId":{"type":"string"},"kind":{"type":"string","enum":["frame","group","rect","ellipse","polygon","line","text","path"]},"name":{"type":"string"},"x":{"type":"string"},"y":{"type":"string"},"width":{"type":"string"},"height":{"type":"string"},"fill_hex":{"type":"string"},"data":{"type":"object","description":"TS-style PenNode data; rich fields are preserved as a subtree"},"postProcess":{"type":"boolean","description":"Accepted for TS compatibility; Rust replace path ignores post-processing"},"canvasWidth":{"type":"number","description":"Accepted for TS compatibility; Rust replace path ignores post-processing width"},"drop_children":{"type":"string","enum":["true","false"]},"dropChildren":{"type":"string","enum":["true","false"]},"pageId":{"type":"string","description":"optional target page id or legacy page index; omitted = active page"}}}}"#,
];

#[cfg(feature = "mcp-debug-tools")]
pub const DEBUG_TOOL_SCHEMAS: &[&str] = &[
    r#"{"name":"debug_validation_report","description":"Run the op-design-lint detectors over the active page and return the design-issue list. Read-only, no parameters. Result: count + categories (`;`-separated `category|count`) + issues (JSON-serialized Issue array). Gated behind the OPENPENCIL_DEBUG_TOOLS=1 env flag.","inputSchema":{"type":"object","properties":{},"additionalProperties":false}}"#,
    r#"{"name":"debug_logs_tail","description":"Read the tail of ~/.openpencil/logs/server-YYYY-MM-DD.log with API keys and Authorization headers redacted. Gated behind OPENPENCIL_DEBUG_TOOLS=1.","inputSchema":{"type":"object","properties":{"tailLines":{"type":"number","description":"Maximum lines to return (default 100, max 500)."},"sinceMs":{"type":"number","description":"Unix ms timestamp; only return lines newer than this."},"grep":{"type":"string","description":"Regex to filter lines by content after redaction."}}}}"#,
    r#"{"name":"debug_screenshot","description":"Capture a PNG screenshot of the live canvas via the renderer. File-backed Rust MCP reports the same no-live-canvas error as TS standalone mode. Gated behind OPENPENCIL_DEBUG_TOOLS=1.","inputSchema":{"type":"object","properties":{"target":{"type":"string","enum":["node","root"]},"nodeId":{"type":"string","description":"Required when target=node."},"padding":{"type":"number"},"dpr":{"type":"number"},"timeoutMs":{"type":"number","description":"Default 15000, max 60000."}},"required":["target"]}}"#,
];

#[cfg(test)]
mod tests {
    #[cfg(feature = "mcp-debug-tools")]
    use super::DEBUG_TOOL_SCHEMAS;
    use super::TOOL_SCHEMAS;

    #[test]
    fn all_array_properties_declare_items() {
        // MCP clients (e.g. the VS Code extension) reject a tool whose
        // inputSchema contains `"type":"array"` without an `items` keyword
        // ("tool parameters array type must have items"). Enumerate every
        // schema property and assert every array declares `items`.
        let catalogs = [
            TOOL_SCHEMAS,
            #[cfg(feature = "mcp-debug-tools")]
            DEBUG_TOOL_SCHEMAS,
        ];
        for catalog in catalogs {
            for raw in catalog {
                let value: serde_json::Value =
                    serde_json::from_str(raw).expect("tool schema must be valid JSON");
                let properties = value["inputSchema"]["properties"]
                    .as_object()
                    .unwrap_or_else(|| {
                        panic!("tool {} must declare inputSchema.properties", value["name"])
                    });
                for (key, prop) in properties {
                    if prop.get("type").and_then(|t| t.as_str()) == Some("array") {
                        assert!(
                            prop.get("items").is_some(),
                            "tool {} property `{key}` is an array but missing `items` — MCP clients \
                             reject schemas without it (tool parameters array type must have items)",
                            value["name"]
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn codegen_schemas_describe_blocking_and_retryable_plan_retention() {
        let schema = |name: &str| {
            TOOL_SCHEMAS
                .iter()
                .find(|schema| schema.contains(&format!(r#""name":"{name}""#)))
                .expect("codegen tool schema")
        };

        let submit = schema("codegen_submit_chunk");
        assert!(submit.contains("Dependent chunks remain blocked"));
        let assemble = schema("codegen_assemble");
        assert!(assemble.contains("Rejects plans with pending chunks"));
        assert!(assemble.contains("retryable partial or degraded results retain it"));
        serde_json::from_str::<serde_json::Value>(assemble).expect("valid assemble schema JSON");
    }

    #[test]
    fn guideline_schema_matches_every_canonical_runtime_topic() {
        let raw = TOOL_SCHEMAS
            .iter()
            .find(|schema| schema.contains(r#""name":"get_guidelines""#))
            .expect("get_guidelines schema");
        let schema: serde_json::Value = serde_json::from_str(raw).expect("guidelines JSON");
        let topics: Vec<&str> = schema["inputSchema"]["properties"]["topic"]["enum"]
            .as_array()
            .expect("topic enum")
            .iter()
            .map(|value| value.as_str().expect("topic string"))
            .collect();
        assert_eq!(topics, op_ai_skills::guideline_topics());
    }

    #[test]
    fn batch_design_schema_is_script_first_and_operations_are_edit_only() {
        let raw = TOOL_SCHEMAS
            .iter()
            .find(|schema| schema.contains(r#""name":"batch_design""#))
            .expect("batch_design schema");
        let schema: serde_json::Value = serde_json::from_str(raw).expect("batch JSON");
        let description = schema["description"].as_str().expect("description");
        let operations = schema["inputSchema"]["properties"]["operations"]["description"]
            .as_str()
            .expect("operations description");
        assert!(description.contains("generate every new UI tree with script"));
        assert!(description.contains("operations is ONLY the edit/refine surface"));
        assert!(operations.contains("Do not use I() here"));
        assert!(!operations.contains("root=I("));
    }

    #[test]
    fn finalize_schema_blocks_presentation_while_advisories_remain() {
        let finalize = TOOL_SCHEMAS
            .iter()
            .find(|schema| schema.contains(r#""name":"finalize_design""#))
            .expect("finalize_design schema");

        assert!(finalize.contains("blockingAdvisoryCount"));
        assert!(finalize.contains("MUST NOT present the design as finished"));
        assert!(finalize.contains("complete=false"));
        serde_json::from_str::<serde_json::Value>(finalize).expect("valid finalize schema JSON");
    }
}
