//! HTML target with inline layout and motion declarations.

use super::{
    codegen_motion_css, emitted_corner_radius, image_object_fit, tabs_nav_markup, widget_markup,
};
use crate::{
    color_to_css, fmt_num, html_escape, node_children, node_fill_css, node_hidden, node_is_ellipse,
    node_is_text, node_origin, node_rotation_deg, node_size, node_stroke_css, node_text,
    root_nodes, Codegen,
};
use jian_ops_schema::node::PenNode;
use jian_ops_schema::PenDocument;

/// HTML + inline-CSS generator. Walks the document's node tree and emits
/// absolutely positioned elements with optional motion declarations.
pub struct Html;

impl Codegen for Html {
    fn target_label(&self) -> &'static str {
        "html"
    }

    fn generate(&self, doc: &PenDocument) -> String {
        let mut out = String::new();
        out.push_str("<!-- Generated by OpenPencil — codegen::Html -->\n");
        out.push_str("<!DOCTYPE html>\n<html><head><meta charset=\"utf-8\">");
        let motion_css = codegen_motion_css::render(doc);
        if !motion_css.is_empty() {
            out.push_str(&format!("<style>\n{motion_css}</style>\n"));
        }
        out.push_str("</head>\n<body>\n");
        for node in root_nodes(doc) {
            emit_node_html(&mut out, node, 1);
        }
        out.push_str("</body></html>\n");
        out
    }
}

pub(super) fn emit_node_html(out: &mut String, node: &PenNode, depth: usize) {
    if node_hidden(node) {
        return;
    }
    let indent = "  ".repeat(depth);
    let tag = if node_is_text(node) { "span" } else { "div" };
    let (x, y) = node_origin(node);
    let (w, h) = node_size(node);
    let mut style = format!(
        "position:absolute;left:{}px;top:{}px;width:{}px;height:{}px",
        fmt_num(x),
        fmt_num(y),
        fmt_num(w),
        fmt_num(h),
    );
    if let Some(fill) = node_fill_css(node) {
        style.push_str(&format!(";background:{}", color_to_css(&fill)));
    }
    if let Some((color, width)) = node_stroke_css(node) {
        style.push_str(&format!(
            ";border:{}px solid {}",
            width,
            color_to_css(&color)
        ));
    }
    let radius = emitted_corner_radius(node);
    if radius > 0.0 {
        style.push_str(&format!(";border-radius:{}px", fmt_num(radius)));
    }
    if node_is_ellipse(node) {
        style.push_str(";border-radius:50%");
    }
    let rotation = node_rotation_deg(node);
    if rotation.abs() > f64::EPSILON {
        style.push_str(&format!(";transform:rotate({}deg)", fmt_num(rotation)));
    }
    style.push_str(&codegen_motion_css::inline_style(node));
    let motion_attr = codegen_motion_css::data_attribute(node);
    if let PenNode::Image(image) = node {
        style.push_str(&format!(
            ";object-fit:{}",
            image_object_fit(node).expect("image fit")
        ));
        out.push_str(&format!(
            "{indent}<img src=\"{}\" alt=\"{}\"{motion_attr} style=\"{style}\" />\n",
            html_escape(image.src.as_ref()),
            html_escape(image.base.name.as_deref().unwrap_or_default()),
        ));
        return;
    }
    // First-class widgets win over the generic div/span heuristic: nest the
    // real form element inside the positioned wrapper.
    if let Some(widget) = widget_markup(node) {
        out.push_str(&format!(
            "{indent}<div{motion_attr} style=\"{style}\">{widget}</div>\n"
        ));
        return;
    }
    if let Some(nav) = tabs_nav_markup(node) {
        out.push_str(&format!(
            "{indent}<div{motion_attr} style=\"{style}\">{nav}"
        ));
        let children = node_children(node);
        if children.is_empty() {
            out.push_str("</div>\n");
        } else {
            out.push('\n');
            for child in children {
                emit_node_html(out, child, depth + 1);
            }
            out.push_str(&format!("{indent}</div>\n"));
        }
        return;
    }
    let body = node_text(node).unwrap_or_default();
    let children = node_children(node);
    if children.is_empty() && body.is_empty() {
        out.push_str(&format!(
            "{indent}<{tag}{motion_attr} style=\"{style}\"></{tag}>\n"
        ));
    } else {
        out.push_str(&format!("{indent}<{tag}{motion_attr} style=\"{style}\">"));
        if !body.is_empty() {
            out.push_str(&html_escape(&body));
        }
        if !children.is_empty() {
            out.push('\n');
            for child in children {
                emit_node_html(out, child, depth + 1);
            }
            out.push_str(&indent);
        }
        out.push_str(&format!("</{tag}>\n"));
    }
}
