//! Owner-only projection of collaboration admission requests.
//!
//! Authentication subjects, device identifiers, profile claims, tickets, and
//! socket addresses stay in the host runtime. Shared UI state receives only a
//! bounded opaque request key, which is sufficient to route an owner decision
//! back to that runtime without turning paint/debug state into an identity
//! side channel.

use std::fmt;
use std::sync::Arc;

use crate::{CollabConnectionPhase, CollabUiRole, CollabUiState};

/// Must not exceed the transport pending-handshake bound.
pub const MAX_COLLAB_PENDING_ADMISSIONS: usize = 16;
/// Keeps malformed host projections from retaining arbitrarily large keys.
pub const MAX_COLLAB_ADMISSION_REQUEST_KEY_BYTES: usize = 96;

/// An epoch-local routing key generated by the host runtime.
///
/// The inner value is intentionally omitted from `Debug`: crash reports and
/// UI model snapshots need to show that a request exists, not how to address
/// its live connection.
#[derive(Clone, PartialEq, Eq, Hash)]
pub struct CollabAdmissionRequestKey(String);

impl CollabAdmissionRequestKey {
    pub fn new(value: impl Into<String>) -> Option<Self> {
        let value = value.into();
        if value.is_empty()
            || value.len() > MAX_COLLAB_ADMISSION_REQUEST_KEY_BYTES
            || !value
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
        {
            return None;
        }
        Some(Self(value))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for CollabAdmissionRequestKey {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("CollabAdmissionRequestKey(<opaque>)")
    }
}

#[derive(Clone, PartialEq, Eq)]
pub struct PendingCollabAdmissionUi {
    request_key: CollabAdmissionRequestKey,
    resume_role: Option<CollabUiRole>,
}

impl PendingCollabAdmissionUi {
    pub fn new(request_key: CollabAdmissionRequestKey, resume_role: Option<CollabUiRole>) -> Self {
        Self {
            request_key,
            resume_role,
        }
    }

    pub fn request_key(&self) -> &CollabAdmissionRequestKey {
        &self.request_key
    }

    /// Same-epoch resumes require a fresh owner decision in M1 and may only
    /// regain the role recorded by the retained session binding.
    pub fn resume_role(&self) -> Option<CollabUiRole> {
        self.resume_role
    }
}

impl fmt::Debug for PendingCollabAdmissionUi {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("PendingCollabAdmissionUi")
            .field("request_key", &self.request_key)
            .field("resume_role", &self.resume_role)
            .finish()
    }
}

impl CollabUiState {
    /// Owner-only view of pending requests. Other roles receive an empty
    /// slice even if a buggy host forgot to clear a stale projection.
    pub fn pending_admissions(&self) -> &[PendingCollabAdmissionUi] {
        if self.phase == CollabConnectionPhase::Active
            && self
                .authenticated_session()
                .is_some_and(|session| session.role == CollabUiRole::Owner)
        {
            self.pending_admissions.as_slice()
        } else {
            &[]
        }
    }

    /// Publishes one authenticated-but-not-authorized request.
    ///
    /// Returns `false` when the caller is not an active owner or the bounded
    /// queue is full. A duplicate key is idempotently accepted.
    pub fn publish_pending_admission(
        &mut self,
        request_key: CollabAdmissionRequestKey,
        resume_role: Option<CollabUiRole>,
    ) -> bool {
        if self.phase != CollabConnectionPhase::Active
            || !self
                .authenticated_session()
                .is_some_and(|session| session.role == CollabUiRole::Owner)
        {
            return false;
        }
        if self
            .pending_admissions
            .iter()
            .any(|request| request.request_key == request_key)
        {
            return true;
        }
        if self.pending_admissions.len() >= MAX_COLLAB_PENDING_ADMISSIONS {
            return false;
        }
        Arc::make_mut(&mut self.pending_admissions)
            .push(PendingCollabAdmissionUi::new(request_key, resume_role));
        self.panel.hover = None;
        true
    }

    pub fn remove_pending_admission(&mut self, request_key: &CollabAdmissionRequestKey) -> bool {
        let pending = Arc::make_mut(&mut self.pending_admissions);
        let before = pending.len();
        pending.retain(|request| request.request_key != *request_key);
        let changed = before != pending.len();
        if changed {
            self.panel.hover = None;
        }
        changed
    }

    pub fn clear_pending_admissions(&mut self) {
        if !self.pending_admissions.is_empty() {
            self.panel.hover = None;
        }
        self.pending_admissions = Arc::new(Vec::new());
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{AuthenticatedCollabSession, CollabAvailability};

    fn key(index: usize) -> CollabAdmissionRequestKey {
        CollabAdmissionRequestKey::new(format!("request-{index}")).unwrap()
    }

    fn active_state(role: CollabUiRole) -> CollabUiState {
        let mut state = CollabUiState::default();
        state.availability = CollabAvailability::Ready;
        assert!(state.set_authenticated_session(
            CollabConnectionPhase::Active,
            AuthenticatedCollabSession {
                session_name: "Design".into(),
                role,
                share_endpoint: None,
            },
            Vec::new(),
        ));
        state
    }

    #[test]
    fn pending_requests_are_owner_only_bounded_and_idempotent() {
        let mut owner = active_state(CollabUiRole::Owner);
        for index in 0..MAX_COLLAB_PENDING_ADMISSIONS {
            assert!(owner.publish_pending_admission(key(index), None));
        }
        assert!(owner.publish_pending_admission(key(0), None));
        assert!(!owner.publish_pending_admission(key(MAX_COLLAB_PENDING_ADMISSIONS), None));
        assert_eq!(
            owner.pending_admissions().len(),
            MAX_COLLAB_PENDING_ADMISSIONS
        );

        let mut viewer = active_state(CollabUiRole::Viewer);
        assert!(!viewer.publish_pending_admission(key(0), None));
        assert!(viewer.pending_admissions().is_empty());
    }

    #[test]
    fn request_key_is_opaque_in_debug_output_and_cleared_with_session() {
        let mut state = active_state(CollabUiRole::Owner);
        let request_key = CollabAdmissionRequestKey::new("secret-routing-token").unwrap();
        assert!(state.publish_pending_admission(request_key.clone(), Some(CollabUiRole::Viewer)));
        assert_eq!(
            state.pending_admissions()[0].resume_role(),
            Some(CollabUiRole::Viewer)
        );
        let debug = format!("{:?}", state.pending_admissions());
        assert!(!debug.contains(request_key.as_str()));
        assert!(state.remove_pending_admission(&request_key));
        assert!(state.pending_admissions().is_empty());

        assert!(state.publish_pending_admission(key(1), None));
        state.clear_authenticated();
        assert!(state.pending_admissions.is_empty());
    }

    #[test]
    fn malformed_or_oversized_request_keys_are_rejected() {
        assert!(CollabAdmissionRequestKey::new("").is_none());
        assert!(CollabAdmissionRequestKey::new("contains:identity").is_none());
        assert!(CollabAdmissionRequestKey::new(
            "a".repeat(MAX_COLLAB_ADMISSION_REQUEST_KEY_BYTES + 1)
        )
        .is_none());
    }
}
